# Generated by Django 3.1 on 2020-09-02 22:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('litter_collection', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bin',
            name='bin_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='litter_collection.bintype'),
        ),
        migrations.AddField(
            model_name='bin',
            name='trash_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='litter_collection.trashtype'),
        ),
    ]
