# Generated by Django 3.1 on 2020-09-02 22:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('litter_collection', '0002_auto_20200902_2239'),
    ]

    operations = [
        migrations.AddField(
            model_name='bin',
            name='bin_district',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='litter_collection.district'),
        ),
    ]
