# Generated by Django 3.1 on 2020-09-09 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('litter_collection', '0003_bin_bin_district'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bin',
            old_name='latitutde',
            new_name='latitude',
        ),
    ]
