/**
 * @author Maksim Sandybekov
 * @date 4.3.2020
 * 
 */


const ADD_DISTRICT = "ADD_DISTRICT";
const REMOVE_DISTRICT = "REMOVE_DISTRICT";

const LOAD_BINS_SUCCESS = "LOAD_BINS_SUCCESS";
const LOAD_BINS_ERROR = "LOAD_BINS_ERROR";

const REMOVE_BIN = "REMOVE_BIN";

const START_ROUTING = "START_ROUTING";
const END_ROUTING = "END_ROUTING";


export {
    ADD_DISTRICT,
    REMOVE_DISTRICT,
    
    LOAD_BINS_SUCCESS,
    LOAD_BINS_ERROR,
    REMOVE_BIN,

    START_ROUTING,
    END_ROUTING
}