/**
 * @author Maksim Sandybekov
 * @date 5.3.2020
 */


 const LOAD_DISTRICTS_SUCCESS = "LOAD_DISTRICTS_SUCCESS";
 const LOAD_DISTRICTS_ERROR = "LOAD_DISTRICTS_ERROR";


 export {
     LOAD_DISTRICTS_SUCCESS,
     LOAD_DISTRICTS_ERROR
 }